version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:7.4-fpm
    container_name: infotech_php
#    network_mode: "host"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
 #     - ./docker/php/image-magic:/etc/ImageMagick-6

  webserver:
    image: nginx:alpine
    container_name: ingotech_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  memcached:
    container_name: infotech_memcached
    image: memcached:latest
    ports:
      - "11211:11211"

  db:
    image: mysql:5.7.24
    container_name: infotech_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: infotech
      MYSQL_USER: infotech
      MYSQL_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/

